/*  =========================================================================
    hydra - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of zbroker, the ZeroMQ broker project.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef HYDRA_LIBRARY_H_INCLUDED
#define HYDRA_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <zyre.h>

//  HYDRA version macros for compile-time API detection
#define HYDRA_VERSION_MAJOR 0
#define HYDRA_VERSION_MINOR 1
#define HYDRA_VERSION_PATCH 0

#define HYDRA_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define HYDRA_VERSION \
    HYDRA_MAKE_VERSION(HYDRA_VERSION_MAJOR, HYDRA_VERSION_MINOR, HYDRA_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined HYDRA_STATIC
#       define HYDRA_EXPORT
#   elif defined HYDRA_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define HYDRA_EXPORT __declspec(dllexport)
#       else
#           define HYDRA_EXPORT
#       endif
#   elif defined HYDRA_EXPORTS
#       define HYDRA_EXPORT __declspec(dllexport)
#   else
#       define HYDRA_EXPORT __declspec(dllimport)
#   endif
#   define HYDRA_PRIVATE
#elif defined (__CYGWIN__)
#   define HYDRA_EXPORT
#   define HYDRA_PRIVATE
#else
#   define HYDRA_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define HYDRA_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define HYDRA_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  HYDRA_BUILD_DRAFT_API
#define HYDRA_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef HYDRA_BUILD_DRAFT_API
typedef struct _hydra_t hydra_t;
#define HYDRA_T_DEFINED
typedef struct _hydra_proto_t hydra_proto_t;
#define HYDRA_PROTO_T_DEFINED
typedef struct _hydra_server_t hydra_server_t;
#define HYDRA_SERVER_T_DEFINED
typedef struct _hydra_client_t hydra_client_t;
#define HYDRA_CLIENT_T_DEFINED
typedef struct _hydra_post_t hydra_post_t;
#define HYDRA_POST_T_DEFINED
typedef struct _hydra_ledger_t hydra_ledger_t;
#define HYDRA_LEDGER_T_DEFINED
#endif // HYDRA_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef HYDRA_BUILD_DRAFT_API
#include "hydra_proto.h"
#include "hydra_server.h"
#include "hydra_client.h"
#include "hydra_post.h"
#include "hydra_ledger.h"
#endif // HYDRA_BUILD_DRAFT_API

#ifdef HYDRA_BUILD_DRAFT_API
//  Self test for private classes
HYDRA_EXPORT void
    hydra_private_selftest (bool verbose);
#endif // HYDRA_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
